name: zawadicash_app
description: The Zawadicash Fintech. Works with all 3 types of customers i.e. Agents, Merchants and Subscribers. Allows you to configure a tariff and apply it to transactions. The project follows DDD principles.

publish_to: 'none'

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  shared_preferences: ^2.0.6
  connectivity_plus: ^4.0.2
  firebase_core: ^2.1.1
  firebase_messaging: ^14.0.3
  flutter_local_notifications: ^15.1.0+1
  path_provider: ^2.0.2
  url_strategy: ^0.2.0
  dotted_border: ^2.0.0+1
  flutter_contacts: ^1.1.4
  azlistview: ^2.0.0
  pin_code_fields: ^8.0.1
  modal_bottom_sheet: ^2.0.0
  slide_to_confirm: ^1.1.0
  lottie: ^2.6.0
  expandable_bottom_sheet: ^1.1.1+1
  smooth_page_indicator: ^1.0.0+2
  image_picker: ^1.0.2
  country_code_picker: ^3.0.0
  camera: ^0.10.0+4
  http: ^0.13.4
  carousel_slider: ^4.0.0
  webview_flutter: ^4.2.2
  flutter_svg: ^2.0.7
  device_preview: ^1.0.0
  flutter_html: ^3.0.0-alpha.1
  shimmer: ^3.0.0
  permission_handler: ^10.0.0
  share_plus: ^7.1.0
  screenshot: ^2.1.0
  gallery_saver: ^2.3.2
  modal_progress_hud_nsn: ^0.4.0
  phone_number: ^2.0.1
  path_drawing: ^1.0.0
  flutter_custom_tabs: ^1.0.4
  local_auth: ^2.1.0
  google_mlkit_barcode_scanning: ^0.9.0
  google_mlkit_face_detection: ^0.8.0
  cached_network_image: ^3.2.2
  flutter_secure_storage: ^8.0.0
  app_settings: ^5.0.0
  percent_indicator: ^4.2.2
  flutter_smart_dialog: ^4.6.2+1
  device_info_plus: ^9.0.3
  unique_identifier: ^0.3.0
  url_launcher: ^6.1.6
  google_barcode_kit: ^0.7.3

dev_dependencies:
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/language/
    - assets/animationFile/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/font/Rubik-Light.ttf
          weight: 300
        - asset: assets/font/Rubik-Regular.ttf
          weight: 400
        - asset: assets/font/Rubik-Medium.ttf
          weight: 500
        - asset: assets/font/Rubik-SemiBold.ttf
          weight: 600